package:
  name: test_pkg
  version:  0.0.0

build:
  script: pip install .

source:
  path: test_pkg


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python

test:
  imports:
    - test_pkg


about:
  home: https://github.com/sot/test_pkg

