name: Share data between jobs

on: [repository_dispatch]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
          mkdir -p builds/linux-64 builds/noarch
          echo one > builds/linux-64/pkg-one
          echo one > builds/linux-64/repodata.json
          echo one > builds/noarch/pkg-two
          echo one > builds/noarch/repodata.json
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt
      - name: Upload packages 1
        uses: actions/upload-artifact@v2
        with:
          name: packages-linux-64
          path: |
            builds/noarch/*
            builds/linux-64/*
            !builds/*/*repodata*

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: homework
          path: .
      - shell: bash
        run: |
          value=`cat math-homework.txt`
          expr $value \* 9 > math-homework.txt
          mkdir -p builds/win-64
          echo two > builds/win-64/pkg-one
          echo two > builds/win-64/repodata.json
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: math-homework.txt
      - name: Upload packages 2
        uses: actions/upload-artifact@v2
        with:
          name: packages-win-64
          path: |
            builds/win-64/*
            !builds/*/*repodata*

  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v1
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat homework/math-homework.txt`
          echo The result is $value
          mkdir -p builds/osx-64
          echo three > builds/osx-64/pkg-one
          echo three > builds/osx-64/repodata.json
      - name: Upload packages 3
        uses: actions/upload-artifact@v2
        with:
          name: packages-osx-64
          path: |
            builds/osx-64/*
            !builds/*/*repodata*

  job_4:
    name: Check
    needs: job_3
    runs-on: ubuntu-latest
    steps:
      - name: Download packages
        uses: actions/download-artifact@v2
        with:
          name: packages-linux-64
          path: .
      - name: Download packages
        uses: actions/download-artifact@v2
        with:
          name: packages-win-64
          path: win-64
      - name: Download packages
        uses: actions/download-artifact@v2
        with:
          name: packages-osx-64
          path: osx-64
      - name: check
        shell: bash
        run: ls -R
