name: Build Ska Package

on:
  repository_dispatch:
    types:
      - build-package-3

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: foo
        uses: skare3/build@main
        with:
          platform: ubuntu-latest
          CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
          CHANDRA_XRAY_TOKEN: ${{ secrets.CHANDRA_XRAY_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

