name: Build Ska Package

on:
  repository_dispatch:
    types:
      - build-package

jobs:
  build:
    uses: sot/skare3/.github/workflows/package_build.yml@speedy-build
    with:
      repository: ${{ github.event.client_payload.package }}
      tag: ${{ github.event.client_payload.tag }}
      noarch: ${{ (github.event.client_payload.arch != 'true') && (github.event.client_payload.arch != 'True')}}
      python_version: "3.11"
      numpy_version: "1.26.2"
      skare3_branch: speedy-build
      # the following channel in ska3-conda is used to create the build environment
      channel: speedy
    secrets:
      CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
      CHANDRA_XRAY_TOKEN: ${{ secrets.CHANDRA_XRAY_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}

  upload:
    if: ${{ (github.event.client_payload.upload == 'true') || (github.event.client_payload.upload == 'True') }}
    needs: [build]
    uses: sot/skare3/.github/workflows/package_upload.yml@speedy-build
    with:
      # this is the destination ska3-conda channel
      channel: speedy
