name: Build One Ska Package


on:
  repository_dispatch:
    types:
      - build-one-package

jobs:
  build:
    runs-on: "ubuntu-latest"
    name: Build on ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Fetch
      uses: actions/checkout@v4
    - name: Fetch Skare3
      uses: actions/checkout@v4
      with:
        repository: sot/skare3
        ref: "master"
        path: skare3
    - name: Fetch Skare3-tools
      uses: actions/checkout@v4
      with:
        repository: sot/skare3_tools
        ref: master
        path: skare3_tools
    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        miniforge-version: latest
        python-version: "3.12"
        activate-environment: conda-build
    - name: Set channels
      run: |
        python --version
        echo "adding flight channel"
        conda config --add channels https://ska:${{ secrets.CONDA_PASSWORD }}@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/flight
        if [[ "${{ github.event.client_payload.with_conda_forge }}" == "true" ]]
        then
          echo "adding conda-forge channel"
          conda config --add channels conda-forge
        fi
        conda config --remove channels defaults  # defaults is added "implicitly" by conda in the previous lines
        conda config --show-sources
        conda config --show channels
    - name: Update Conda Environment
      run: |
        conda list ^python$ --export | grep python >> $CONDA_PREFIX/conda-meta/pinned
        conda env update -n conda-build -f ./skare3/build-environment.yml
    - name: Install ska_helpers
      run: |
        ${CONDA_EXE} install ska_helpers
        ${CONDA_EXE} install testr
    - name: Env List
      run: conda list
    - name: Build Package
      working-directory: skare3
      run: |
        python ska_builder.py  ${{ github.event.client_payload.repository }} --tag ${{ github.event.client_payload.tag }} -c https://ska:${{ secrets.CONDA_PASSWORD }}@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/flight -c conda-forge
      env:
        CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
        GIT_USERNAME: chandra-xray
        GIT_ASKPASS: ${{ github.workspace }}/skare3_tools/actions/build/files/git_pass.py
        GIT_PASSWORD: ${{ secrets.CHANDRA_XRAY_TOKEN }}
    - name: Summary
      run: |
        files=`find  builds/noarch/ builds/linux-64/ builds/osx-64/ builds/osx-arm64/ builds/win-64/ -not -name \*repodata\* -not -name index.html -not -name .ensure-non-empty-dir -type f`
        echo "## Packages Built:" >> $GITHUB_STEP_SUMMARY
        for f in $files; do echo "- $f" >> $GITHUB_STEP_SUMMARY; done;

