name: Conda build release
on:
  workflow_dispatch:
    inputs:
      skare3_ref:
        description: 'Full skare3 ref to build (e.g. refs/tags/v2024.10)'
        required: false
        type: string
        default: '2026.7rc1'

env:
  SKARE3_REF: ${{ inputs.skare3_ref }}

jobs:
  build:
    runs-on: "windows-2022"
    name: Build
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Fetch Skare3
      uses: actions/checkout@v4
      with:
        repository: sot/skare3
        ref: ${{ inputs.skare3_ref }}
        path: skare3
    - name: Fetch Skare3-tools
      uses: actions/checkout@v4
      with:
        repository: sot/skare3_tools
        ref: master
        path: skare3_tools
    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v3.2.0
      with:
        auto-update-conda: true
        miniforge-version: latest
        python-version: "3.13"
        activate-environment: conda-build
        channels: conda-forge
    - name: Add flight channel
      run: conda config --env --add channels https://ska:${{ secrets.CONDA_PASSWORD }}@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/test
    - name: temprarily use classic solver
      run: conda config --set solver classic
    - name: Update Conda Environment
      run: conda env update -n conda-build -f ./skare3/build-environment.yml
    - name: List Conda Packages
      run: conda list
    - name: Update Conda Environment
      run: conda install -n base -c conda-forge conda-build
    - name: Update Conda Environment
      run: conda build --help
    - name: Build Package
      run: |
        for package in ska3-core ska3-core-latest; do
          python skare3_tools/skare3_tools/scripts/build.py ${package} \
          --arch-specific --tag ${SKARE3_REF} --skare3-branch ${SKARE3_REF} --skare3-overwrite-version 2026.7:2026.7rc1;
        done;
      env:
        CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
        GIT_USERNAME: chandra-xray
        GIT_ASKPASS: ${{ github.workspace }}/skare3_tools/actions/build/files/git_pass.py
        GIT_PASSWORD: ${{ secrets.CHANDRA_XRAY_TOKEN }}
    - name: Review built packages
      run: ls -l builds/*
    - name: Save package
      uses: actions/upload-artifact@v4
      with:
        name: conda-package-${{ matrix.os }}
        path: |
          builds/noarch/
          builds/linux-64/
          builds/osx-64/
          builds/osx-arm64/
          builds/win-64/
          !builds/*/*repodata*
          !builds/*/index.html

