name: Build One Ska Package


on:
  repository_dispatch:
    types:
      - build-one-package

jobs:
  build:
    runs-on: "ubuntu-latest"
    name: Build on ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Fetch
      uses: actions/checkout@v4
    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        miniforge-version: latest
        python-version: "3.12"
        activate-environment: conda-build
    - name: Set channels
      run: |
        python --version
        echo "adding conda-forge channel"
        conda config --add channels conda-forge
        conda config --remove channels defaults  # defaults is added "implicitly" by conda in the previous lines
        conda config --show-sources
        conda config --show channels
    - name: Update Conda Environment
      run: |
        conda list ^python$ --export | grep python >> $CONDA_PREFIX/conda-meta/pinned
        conda install python six pytables numpy numexpr chandra_time ska_path astropy h5py testr ska_helpers
    - name: Env List
      run: conda list
    - name: Build Package
      run: |
        pwd
        ls
        conda build test_pkg --croot builds --old-build-string --no-anaconda-upload --python 3.12 --numpy 1.26 --perl 5.32.1 -c conda-forge --no-test
        echo ls -R builds
        ls -R builds


