name: Conda build

on:
  repository_dispatch:
    types:
      - conda-build-macos

jobs:
  build-other:
    runs-on: ${{ matrix.os }}-latest
    name: Build on ${{ matrix.os }}
    if: ${{
        github.event.client_payload.package &&
        github.event.client_payload.tag &&
        github.event.client_payload.arch
      }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos"]
    steps:
    - name: Fetch Skare3-tools
      uses: actions/checkout@v2
      with:
        repository: sot/skare3_tools
        ref: shiny
        path: skare3_tools
    - uses: sot/setup-miniconda@v2
      with:
        miniconda-version: "py38_4.8.3"
        python-version: "3.8"
        channels: https://ska:${{ secrets.CONDA_PASSWORD }}@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/shiny
    - name: Build Dependencies
      shell: bash -l {0}
      run: conda install setuptools_scm gitpython conda-build jinja2 pyyaml python=3.8 numpy packaging
    - name: Build Package
      shell: bash -l {0}
      run: |
        TAG=${{ github.event.client_payload.tag }}
        PACKAGE=${{ github.event.client_payload.package }}
        sudo xcode-select -s "/Applications/Xcode_12.3.app"
        python skare3_tools/actions/build/files/build.py \
        ${PACKAGE} --force --tag ${TAG}
      env:
        CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
        GIT_USERNAME: chandra-xray
        GIT_ASKPASS: ${{ github.workspace }}/skare3_tools/actions/build/files/git_pass.py
        GIT_PASSWORD: ${{ secrets.CHANDRA_XRAY_TOKEN }}
    - name: Save package
      uses: actions/upload-artifact@v2
      with:
        name: conda-package
        path: |
          builds/osx-64/
          builds/win-64/
          !builds/*/*repodata*
          !builds/*/index.html
