name: Build Ska Package

on:
  repository_dispatch:
    types:
      - build-package

jobs:
  build:
    uses: sot/skare3/.github/workflows/package_build.yml@master
    with:
      repository: ${{ github.event.client_payload.package }}
      tag: ${{ github.event.client_payload.tag }}
      noarch: ${{ !github.event.client_payload.arch }}
    secrets:
      CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
      CHANDRA_XRAY_TOKEN: ${{ secrets.CHANDRA_XRAY_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}

  upload:
    if: ${{ github.event.client_payload.upload }}
    needs: [build]
    uses: sot/skare3/.github/workflows/package_upload.yml@master
