name: Parse Arguments

on:
  repository_dispatch:
    types:
      - parse-arguments

jobs:
  build:
    runs-on: ubuntu-latest
    name: Arguments
    outputs:
      name: ${{ fromJson(steps.arguments.outputs.arguments).name }}
      age: ${{ fromJson(steps.arguments.outputs.arguments).age }}
      occupation: ${{ fromJson(steps.arguments.outputs.arguments).occupation }}
      comments: ${{ fromJson(steps.arguments.outputs.arguments).comments }}
    steps:
      - id: arguments
        uses: skare3/check-arguments@main
        with:
          arguments: |
            - name: name
              required: true
            - name: age
              required: true
            - name: occupation
              required: false
              default: "unemployed"
            - name: comments
              required: false
      - name: Print Arguments
        run: |
          echo "Name: ${{ fromJson(steps.arguments.outputs.arguments).name }}" >> $GITHUB_STEP_SUMMARY
          echo "Age: ${{ fromJson(steps.arguments.outputs.arguments).age }}" >> $GITHUB_STEP_SUMMARY
          echo "Occupation: ${{ fromJson(steps.arguments.outputs.arguments).occupation }}" >> $GITHUB_STEP_SUMMARY
          echo "Comments: ${{ fromJson(steps.arguments.outputs.arguments).comments }}" >> $GITHUB_STEP_SUMMARY

  summary:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print Arguments
        run: |
          echo "Name: ${{ needs.build.outputs.name }}" >> $GITHUB_STEP_SUMMARY
          echo "Age: ${{ needs.build.outputs.age }}" >> $GITHUB_STEP_SUMMARY
          echo "Occupation: ${{ needs.build.outputs.occupation }}" >> $GITHUB_STEP_SUMMARY
          echo "Comments: ${{ needs.build.outputs.comments }}" >> $GITHUB_STEP_SUMMARY