name: Parse Arguments

on:
  repository_dispatch:
    types:
      - parse-arguments

jobs:
  build:
    runs-on: ubuntu-latest
    name: An example parsing arguments
    steps:
      - uses: skare3/check-arguments@main
        with:
          arguments: |
            - name: name
              required: true
            - name: age
              required: true
            - name: occupation
              required: false
              default: "unemployed"
            - name: comments
              required: false
