name: Parse Arguments

on:
  repository_dispatch:
    types:
      - parse-arguments

jobs:
  build:
    runs-on: ubuntu-latest
    name: Arguments
    steps:
      - id: arguments
        uses: skare3/check-arguments@main
        with:
          arguments: |
            - name: name
              required: true
            - name: age
              required: true
            - name: occupation
              required: false
              default: "unemployed"
            - name: comments
              required: false

      - name: Print Arguments
        run: |
          echo "Status: ${{ steps.arguments.outputs.status }}"
          echo "Name: ${{ steps.arguments.outputs.name }}" >> $GITHUB_STEP_SUMMARY
          echo "Age: ${{ steps.arguments.outputs.age }}" >> $GITHUB_STEP_SUMMARY
          echo "Occupation: ${{ steps.arguments.outputs.occupation }}" >> $GITHUB_STEP_SUMMARY
          echo "Comments: ${{ steps.arguments.outputs.comments }}" >> $GITHUB_STEP_SUMMARY