name: Parse Arguments

on:
  repository_dispatch:
    types:
      - parse-arguments

jobs:
  build:
    runs-on: ubuntu-latest
    name: Arguments
    outputs:
      name: ${{ steps.arguments.outputs.name }}
      age: ${{ steps.arguments.outputs.age }}
      occupation: ${{ steps.arguments.outputs.occupation }}
      comments: ${{ steps.arguments.outputs.comments }}
      status: ${{ steps.arguments.outputs.status }}
    steps:
      - id: arguments
        uses: skare3/check-arguments@main
        with:
          arguments: |
            - name: name
              required: true
            - name: age
              required: true
            - name: occupation
              required: false
              default: "unemployed"
            - name: comments
              required: false
      - name: Print Arguments
        run: |
          echo "Arguments: ${{ steps.arguments.outputs.arguments }}" >> $GITHUB_STEP_SUMMARY
          echo "Name: ${{ fromJson(steps.arguments.outputs.arguments).name }}" >> $GITHUB_STEP_SUMMARY

  summary:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print Arguments
        run: |
          echo "Status: ${{ needs.build.outputs.status }}" >> $GITHUB_STEP_SUMMARY
          echo "Name: ${{ needs.build.outputs.name }}" >> $GITHUB_STEP_SUMMARY
          echo "Age: ${{ needs.build.outputs.age }}" >> $GITHUB_STEP_SUMMARY
          echo "Occupation: ${{ needs.build.outputs.occupation }}" >> $GITHUB_STEP_SUMMARY
          echo "Comments: ${{ needs.build.outputs.comments }}" >> $GITHUB_STEP_SUMMARY