name: Tests

on: [push]

jobs:
  check:
    runs-on: head
    name: Tests
    steps:
      - name: Fetch
        uses: actions/checkout@v2
      - name: Pytest
        run: |
          source /export/jgonzale/github-workflows/miniconda3/envs/ska3-masters/bin/ska_envs.sh
          pytest Quaternion
