name: Parse Arguments

on:
  repository_dispatch:
    types:
      - parse-arguments

jobs:
  build:
    runs-on: ubuntu-latest
    name: An example parsing arguments
    steps:
      - uses: skare3/check-arguments@main
        with:
          arguments: |
            ubuntu-latest
      - name: Print Arguments
        shell: bash
        run: |
          echo Arguments: "${{ toJson(github.event.client_payload) }}"


