name: Repository Dispatch

on:
  repository_dispatch:
    types:
    - dispatch-test

jobs:
  dispatch-test:
    runs-on: ubuntu-latest
    name: Dispatch Test
    steps:
      - name: Dispatch Test
        if: ${{ github.event.client_payload.name }}
        run: |
          echo name: ${{ github.event.client_payload.name }}
