on:
  repository_dispatch:
    types:
      - miniforge-test

jobs:
  build:
    runs-on: ubuntu-latest
    name: Miniforge
    steps:
    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
    - name: Env List
      run: |
        conda config --show channels
        conda list
