on:
  repository_dispatch:
    types:
      - miniforge

jobs:
  build:
    runs-on: ubuntu-latest
    name: Miniforge
    steps:
    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        # miniforge-version: latest
        python-version: 3.11
        conda-remove-defaults: "true"
        channels: conda-forge
        # mamba-version: "*"
    - name: Set channels
      run: |
        conda config --show channels
        conda config --add channels https://ska:${{ secrets.CONDA_PASSWORD }}@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/flight
        conda config --show channels
        conda config --remove channels https://repo.anaconda.com/pkgs/main
        conda config --remove channels https://repo.anaconda.com/pkgs/r
    - name: Env List
      run: |
        conda config --show channels
        conda list
