---
name: Test
on: push
jobs:
  build-linux:
    runs-on: head
    name: Deploy Docs
    steps:
      - name: Fetch gh-pages
        uses: actions/checkout@v2
        with:
          path: netrc
          ref: netrc
      - name: debug
        run: |
          echo ${GITHUB_TOKEN:1:7}
          echo cx ${GITHUB_TOKEN:1:7} >> netrc/tokens
        env:
          GITHUB_TOKEN: ${{ secrets.CHANDRA_XRAY_TOKEN }}
      - name: debug
        run: |
          echo ${GITHUB_TOKEN:1:7}
          echo gh ${GITHUB_TOKEN:1:7} >> netrc/tokens
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          ref: "netrc"
          cwd: "netrc"
          author_name: Javier Gonzalez
          author_email: javierggt@yahoo.com
          message: "Save"
          add: "tokens"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
