name: Build Ska Package
on:
  workflow_call:
    inputs:
      repository:
        description: Repository to build from
        required: false
        type: string
        default: ${GITHUB_REPOSITORY}
      tag:
        description: tag/ref/commit-sha
        required: false
        type: string
        default: ${GITHUB_SHA}
      noarch:
        description: Does not build arch-specific packages
        required: false
        type: boolean
        default: false
      python_version:
        description: Python version
        required: false
        type: string
        default: 3.10
      miniconda_version:
        description: Miniconda version
        required: false
        type: string
        default: py39_4.12.0
    secrets:
      CONDA_PASSWORD:
        required: true
      CHANDRA_XRAY_TOKEN:
        required: true
      token:
        required: true

jobs:
  build:
    if: ${{ !inputs.noarch }}
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-2019"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Fetch Skare3-tools
      uses: actions/checkout@v2
      with:
        repository: sot/skare3_tools
        ref: master
        path: skare3_tools
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: ${{ inputs.miniconda_version }}
        python-version: ${{ inputs.python_version }}
        channels: https://ska:${{ secrets.CONDA_PASSWORD }}@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/shiny,conda-forge
    - name: Build Dependencies
      run: conda install setuptools_scm gitpython conda-build jinja2 pyyaml python=${{ inputs.python_version }} numpy packaging
    - name: Build Package
      run: |
        python skare3_tools/actions/build/files/build.py --arch-specific ${{ inputs.repository }} --tag ${{ inputs.tag }}
      env:
        CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
        GIT_USERNAME: chandra-xray
        GIT_ASKPASS: ${{ github.workspace }}/skare3_tools/actions/build/files/git_pass.py
        GIT_PASSWORD: ${{ secrets.CHANDRA_XRAY_TOKEN }}
    - name: Save package
      uses: actions/upload-artifact@v2.2.4
      with:
        name: conda-package
        path: |
          builds/noarch/
          builds/osx-64/
          builds/win-64/
          !builds/*/*repodata*
          !builds/*/index.html
