name: Build Ska Package
on:
  workflow_call:
    inputs:
      repository:
        description: Repository to build from
        required: false
        type: string
        default: ${GITHUB_REPOSITORY}
      tag:
        description: tag/ref/commit-sha
        required: false
        type: string
        default: ${GITHUB_SHA}
      noarch:
        description: Does not build arch-specific packages
        required: false
        type: boolean
        default: false
      xcode:
        description: XCode directory
        required: false
        type: string
        default: /Applications/Xcode_14.1.app
    secrets:
      CONDA_PASSWORD:
        required: true
      CHANDRA_XRAY_TOKEN:
        required: true
      token:
        required: true

jobs:
  build-other:
    if: ${{ !inputs.noarch }}
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
    steps:
    - name: Fetch Skare3-tools
      uses: actions/checkout@v2
      with:
        repository: sot/skare3_tools
        ref: master
        path: skare3_tools
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "py38_4.12.0"
        python-version: "3.8"
        channels: https://ska:${{ secrets.CONDA_PASSWORD }}@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/shiny
    - name: Show channels
      run: conda config --show channels
    - name: Build Dependencies
      shell: bash -l -e {0}
      run: conda install setuptools_scm gitpython conda-build jinja2 pyyaml python=3.8 numpy packaging
    - name: Build Package
      shell: bash -l -e {0}
      run: |
        python skare3_tools/actions/build/files/build.py --arch-specific ${{ inputs.repository }} --tag ${{ inputs.tag }}
      env:
        CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
        GIT_USERNAME: chandra-xray
        GIT_ASKPASS: ${{ github.workspace }}/skare3_tools/actions/build/files/git_pass.py
        GIT_PASSWORD: ${{ secrets.CHANDRA_XRAY_TOKEN }}
    - name: Save package
      uses: actions/upload-artifact@v2.2.4
      with:
        name: conda-package
        path: |
          builds/noarch/
          builds/osx-64/
          builds/win-64/
          !builds/*/*repodata*
          !builds/*/index.html
