name: Release
on:
  release:
    types:
      - released

jobs:

  sanity_check:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.sanity_check.outputs.packages }}
      prerelease: ${{ steps.sanity_check.outputs.prerelease }}
    steps:
    - name: Checkout skare3
      uses: actions/checkout@v2
      with:
        repository: sot/skare3
        ref: 2020.9
        path: skare3
    - name: Fetch Skare3 Tools
      uses: actions/checkout@v2
      with:
        repository: sot/skare3_tools
        ref: master
        path: skare3_tools
    - id: sanity_check
      run: |
        sudo pip3 install setuptools
        sudo pip3 install -r ./skare3_tools/requirements.txt
        sudo pip3 install ./skare3_tools
        skare3-release-check --skare3-path ./skare3 --version $GITHUB_REF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_API_TOKEN: ${{ secrets.CHANDRA_XRAY_TOKEN }}

