name: Setup Miniconda

on:
  repository_dispatch:
    types:
      - setup-miniconda

jobs:
  setup:
    runs-on: "macos-latest"
    name: Setup
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Fetch Skare3-tools
      uses: actions/checkout@v2
      with:
        path: .
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "py38_4.8.3"
        python-version: "3.10"
        environment-file: build-environment.yml
        channels: ttps://ska:${{ secrets.CONDA_PASSWORD }}@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/flight
    # - name: Remove defaults channel
    #   run: conda config --remove channels defaults
    - name: Show channels
      run: conda config --show channels
    - name: condarc
      run: cat /Users/runner/.condarc
    - name: list
      run: conda list
