---
name: Test Setup
on:
  repository_dispatch:
    types: [test-setup]

jobs:
  build-conda:
    runs-on: windows-latest
    name: Test
    steps:
      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
      - name: Conda build
        if: ${{ github.event.client_payload.build }}
        shell: bash -l {0}
        run: |
          pwd
          ls
          conda list
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: conda-incubator/setup-miniconda
          ref: master
          path: setup
      - name: Change directory
        shell: bash -l {0}
        run: |
          pwd
          ls
          cd setup
          pwd
          ls
