---
name: Ska3 conda meta.yaml
on:
  repository_dispatch:
    types: [test-setup]

jobs:
  build-conda:
    runs-on: ${{ matrix.os }}-latest
    name: Build ${{ matrix.os }} conda meta-packages
    strategy:
      fail-fast: false
      matrix:
        os: ["windows"]
    steps:
      - name: Setup conda environment
        uses: sot/setup-miniconda@v2
        with:
          miniconda-version: "py38_4.8.3"
          python-version: "3.8"
      - name: Debug 1
        shell: bash -l {0}
        run: |
          pwd
          ls
      - name: Checkout Skare3
        uses: actions/checkout@v2
        with:
          repository: sot/skare3
          ref: ${{ github.event.client_payload.skare3_branch }}
          path: skare3
      - name: Copy yaml files
        shell: bash -l {0}
        run: |
          pwd
          ls
