---
name: Ska3 conda meta.yaml
on:
  repository_dispatch:
    types: [test-setup]

jobs:
  build-conda:
    runs-on: windows-latest
    name: Test
    steps:
      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "py38_4.8.3"
          python-version: "3.8"
      - name: Setup build environment
        if: ${{ github.event.client_payload.build }}
        shell: bash -l {0}
        run: |
          pwd
          ls
          conda install conda-build gitpython git
          pwd
          ls
      - name: Checkout Skare3
        uses: actions/checkout@v2
        with:
          repository: conda-incubator/setup-miniconda
          ref: master
          path: setup
      - name: Copy yaml files
        shell: bash -l {0}
        run: |
          pwd
          ls
          cd setup
