name: Build Ska Package

on:
  repository_dispatch:
    types:
      - test-dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Package: ${{ github.event.client_payload.package }}"
        echo "Tag: ${{ github.event.client_payload.tag }}"
        echo "Arch: ${{ github.event.client_payload.arch }}"
        echo "Upload: ${{ github.event.client_payload.upload }}"
        echo "Python version: ${{ github.event.client_payload.python_version }}"
        echo "Numpy version: ${{ github.event.client_payload.numpy_version }}"
        echo "Input channel: ${{ github.event.client_payload.channel }}"
      shell: bash
    - run: |
        python=${{ github.event.client_payload.python_version }}
        if [ "$python" == "" ]; then echo "PYTHON_VERSION=${python}" >> $GITHUB_STATE else echo "PYTHON_VERSION=3.11" fi
        if [ "${{ github.event.client_payload.upload }}" == "" ]; then echo upload is not given; fi
        if [ "${{ github.event.client_payload.upload }}" == "false" ]; then echo upload is false; fi
        if [ "${{ github.event.client_payload.upload }}" == "False" ]; then echo upload is False; fi
    - if: ${{ github.event.client_payload.upload }}
      run: echo "Uploading"
    - run: echo python version: $PYTHON_VERSION
  

